# Generated by Django 3.2.6 on 2021-09-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
